/**
 * @file ad_gateway_drv.h
 * @author Jan Łukaszewicz (pldevluk@gmail.com)
 * @brief Hardware-agnostic interface for network and MQTT gateway drivers.
 * @version 1.0
 * @date 06-05-2026
 * @copyright The MIT License (MIT) Copyright (c) 2026 
 * 
 * @defgroup device_gateway_drv_api Abstract Gateway Driver API
 * @ingroup device_mqtt_gateway
 * @brief Defines the abstract driver interface for modem control and MQTT operations.
 * 
 * @details This interface acts as a hardware abstraction layer. Hardware-specific 
 * drivers (e.g., ESP32 SIM800 driver) must implement the `ad_gw_drv_t` structure. 
 * This allows the upper application layer to interact with the network and MQTT 
 * without knowing the underlying hardware details.
 * 
 * @{
 */

#ifndef AD_GATEWAY_DRV_H_
#define AD_GATEWAY_DRV_H_

#include "stdint.h"

#define AD_GW_DRV_MQTT_MAX_TOPIC_LEN    64
#define AD_GW_DRV_MQTT_MAX_DATA_LEN     512

/**
 * @brief Gateway driver lifecycle and state events.
 * 
 * @details These events are generated by the underlying hardware driver and 
 * pushed to the application layer via the registered callback function.
 */
typedef enum {
    AD_GW_DRV_CONNECTED = 0,         ///< Physical network layer connected.
    AD_GW_DRV_DISCONNECTED,          ///< Physical network layer disconnected.
    AD_GW_DRV_GOT_IP,                ///< Tunnel established, IP address assigned (e.g., LwIP PPP).
    AD_GW_DRV_LOST_IP,               ///< Tunnel dropped, IP address lost.

    AD_GW_DRV_MQTT_CONNECTED,        ///< MQTT client successfully connected to the broker.
    AD_GW_DRV_MQTT_DISCONNECTED,     ///< MQTT client connection dropped.
    AD_GW_DRV_MQTT_SUBSCRIBED,       ///< Successfully subscribed to an MQTT topic.
    AD_GW_DRV_MQTT_UNSUBSCRIBED,     ///< Successfully unsubscribed from an MQTT topic.
    AD_GW_DRV_MQTT_PUBLISHED,        ///< Message successfully published to the broker.
    AD_GW_DRV_MQTT_DATA,             ///< Incoming MQTT message received.
    AD_GW_DRV_MQTT_ERROR,            ///< General MQTT protocol or transport error.

    AD_GW_DRV_END_OF_EVENT           ///< End of events enum marker.
} ad_gw_drv_event_t;

typedef struct {
    char topic[AD_GW_DRV_MQTT_MAX_TOPIC_LEN];
    char data[AD_GW_DRV_MQTT_MAX_DATA_LEN];
} ad_gw_drv_mqtt_data_t;

/**
 * @brief Event callback function signature.
 * 
 * @param event The triggered driver event from `ad_gw_drv_event_t`.
 * @param context Optional context data associated with the event (e.g., pointer to MQTT message struct).
 */
typedef void (*ad_gw_drv_event_cb_t)(ad_gw_drv_event_t event, void *context);

/**
 * @brief Hardware-agnostic Gateway Driver Interface.
 * 
 * @details Contains function pointers that must be implemented by the 
 * hardware-specific layer. The upper application uses this struct to 
 * control the modem and send/receive MQTT data.
 */
typedef struct {
    /**
     * @brief Initializes the driver (allocates interfaces, registers events, starts HW tasks).
     * @return 0 on success, negative error code on failure.
     */
    int8_t (*init)(void);
    
    /**
     * @brief Modem control interface.
     */
    struct {
        /**
         * @brief Starts the network connection process and PPP negotiation.
         * @return 0 on success, negative error code on failure.
         */
        int8_t (*connect)(void);
        
        /**
         * @brief Checks the current physical connection status.
         * @return 0 if connected, negative error code otherwise.
         */
        int8_t (*connectCheck)(void);
        
        /**
         * @brief Gracefully powers down the modem and closes network interfaces.
         * @return 0 on success, negative error code on failure.
         */
        int8_t (*disconnect)(void);
    } modem;
    
    /**
     * @brief MQTT control interface.
     */
    struct {
        /**
         * @brief Publishes an MQTT message to a specific topic.
         * @param topic Target MQTT topic.
         * @param payload Message payload (byte array).
         * @param len Payload length in bytes.
         * @param qos Quality of Service (0, 1, or 2).
         * @param retain Retain flag (1 to retain message on broker, 0 otherwise).
         * @return 0 on success, negative error code on failure.
         */
        int8_t (*publish)(const char *topic, const uint8_t *payload, uint16_t len, uint8_t qos, uint8_t retain);
        
        /**
         * @brief Subscribes to an MQTT topic.
         * @param topic Topic pattern to subscribe to.
         * @param qos Quality of Service requested.
         * @return 0 on success, negative error code on failure.
         */
        int8_t (*subscribeSingle)(const char *topic, uint8_t qos);
        
        /**
         * @brief Unsubscribes from an MQTT topic.
         * @param topic Topic pattern to unsubscribe from.
         * @return 0 on success, negative error code on failure.
         */
        int8_t (*unSubscribeSingle)(const char *topic);   
    } mqtt;
} ad_gw_drv_t;

/**
 * @brief Registers the upper-layer callback for hardware driver events.
 * 
 * @details This function acts as an Inversion of Control (IoC) mechanism. 
 * Its prototype is defined in this abstract header, but its **implementation 
 * must be provided by the underlying hardware-specific driver** (e.g., `ad_gateway_drv_esp32.c`).
 * 
 * The upper management layer (e.g., `ad_gateway`) calls this function to inject 
 * its listener, allowing the hardware layer to asynchronously push notifications 
 * (such as IP allocation, connection drops, or MQTT events) upwards.
 * 
 * @note This should be called before invoking the driver's `init()` function 
 * to ensure no early boot events (e.g., `AD_GW_DRV_GOT_IP`) are missed.
 * 
 * @param callback Function pointer to the upper-layer event handler.
 */
void ad_gw_drv_register_event_cb(ad_gw_drv_event_cb_t callback);

#endif  /* AD_GATEWAY_DRV_H_ */

/** @} */