TARGET=template



# source file
SRC_FILES = \
../../src/periphery/f411_usart.c \
../../src/my_math.c 

TEST_FILES = \
test_runner.c \
template_test.c

# include paths
INC = \
-I ../common \
-I ../../src \
-I ../../src/periphery \
-I ../../src/sys/CMSIS 




SYS_FILES = \
../../src/sys/syscalls.c\
../../src/sys/startup_stm32f411retx.s

COMMON_FILES = \
../common/unity_fixture.c \
../common/unity.c \
../common/unity_runner.c





include ../common/common.mk